name: LPC
version: '${version}'
main: de.ayont.lpc.LPC
api-version: '1.21'
authors: [Ayont, Varilx-Development, Earth1283]
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
description: LPC, but FOSS with supposed premium featuers made free
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"
  msg:
    description: Send a private message to a player.
    aliases: [whisper, tell, w, m, t]
    permission: lpc.msg
    usage: "Usage: /msg <player> <message>"
  reply:
    description: Reply to the last private message.
    aliases: [r]
    permission: lpc.reply
    usage: "Usage: /r <message>"
  socialspy:
    description: Toggle Social Spy mode.
    aliases: [ss]
    permission: lpc.socialspy
    usage: "Usage: /socialspy"
  ignore:
    description: Ignore another player.
    permission: lpc.ignore
    usage: "Usage: /ignore <player>"
  staffchat:
    description: Send a message to the staff channel.
    aliases: [sc]
    permission: lpc.staffchat
    usage: "Usage: /sc <message>"
  chatclear:
    description: Clear the chat.
            aliases: [cc]
            permission: lpc.chatclear
            usage: "Usage: /chatclear"
          channel:
            description: Manage chat channels.
            aliases: [ch]
            permission: lpc.channel.use
            usage: "Usage: /ch [channel] [message]"
        
        permissions:
          lpc.reload:
        
        description: Allows reloading the configuration.
        default: op
      lpc.msg:
        description: Allows sending private messages.
        default: true
      lpc.reply:
        description: Allows replying to private messages.
        default: true
      lpc.socialspy:
        description: Allows using social spy.
        default: op
      lpc.ignore:
        description: Allows ignoring players.
        default: true
      lpc.staffchat:
        description: Allows using staff chat.
        default: op
      lpc.chatclear:
        description: Allows clearing the chat.
        default: op
      lpc.bubbles.toggle:
        description: Allows toggling chat bubbles for oneself.
        default: true
    